### ISSUE TITLE
Rich text editor loads content correctly but does not display it within the field

### ISSUE THREAD

**Issue by vkononov** [konstantinmuenster/strapi-plugin-rich-text#4]
I love your plugin, and just started exploring in the development environment, but very quickly ran into a very serious issue that makes the plugin unusable in production.

What happens is that any text entered into the rich text fields is saved but disappears on page refresh. It persists in the database, but simply does not display. I've attached a video to demonstrate.

**My environment:**

- OS: macOS Sonoma 14.5 (23F79)
- Browser: Safari v17.5 (19618.2.12.11.6)
- Node: v18.20.3
- MySQL: Ver 8.4.0 for macos14 on x86_64 (MySQL Community Server - GPL)

**Attachments:**

- Database dump: [database.sql.zip](https://github.com/user-attachments/files/16089095/database.sql.zip)
- Code repository: [example_app.zip](https://github.com/user-attachments/files/16089085/example_app.zip)

Below is a video that showcases the problem.

https://github.com/konstantinmuenster/strapi-plugin-rich-text/assets/2658606/06724842-ae15-4462-b093-7938026a312d

**Comment by konstantinmuenster** [comment]
Hey @vkononov and thanks for opening this issue!

Just to make sure, you don't see any related errors in the console or on the server?

**Comment by vkononov** [comment]
@konstantinmuenster That's right. I do not see any errors whatsoever in either the JavaScript console or in the Strapi server logs. I've tried debugging this for a long time, but I have little familiarity with the inner workings of Strapi, so it is a challenging task.

Thanks for looking into this. 😊

**Comment by delux220** [comment]
I'm experiencing this issue as well.

**Comment by delux220** [comment]
@konstantinmuenster @vkononov 
I was on Strapi 4.25 and reverted back to 4.17.0.  The plugin works now. I'm not sure where, between 4.17 and 4.25, it broke however.

**Comment by vkononov** [comment]
@konstantinmuenster You're right. Not seeing an issue in 4.17.0. Though I thought it briefly worked in 4.25.2, but maybe I am misremembering.

**Comment by konstantinmuenster** [comment]
Thanks a lot for the investigation (and workaround)! I'll look into it.

**Comment by SalahAdDin** [comment]
> Thanks a lot for the investigation (and workaround)! I'll look into it.

are you planning to port this package to Strapi 5?

**Comment by konstantinmuenster** [comment]
I just published a new release (v1.2.1) which should fix the issue 🤞

**Comment by konstantinmuenster** [comment]
> > Thanks a lot for the investigation (and workaround)! I'll look into it.
> 
> @konstantinmuenster, are you planning to port this package to Strapi 5?

If there are some issues around Strapi 5, please open a separate issue here on Github. But Strapi 5 will be definitely supported 👌

**Comment by delux220** [comment]
With Strapi 4.25.1 and strapi-plugin-rich-text 1.2.1 I see the following:
<img width="1031" alt="Screenshot 2024-07-15 at 2 14 29 PM" src="https://github.com/user-attachments/assets/cf2610d8-ac41-41df-9b9b-427ff3585ee2">
Both fields are strapi-plugin-rich-text

**Comment by konstantinmuenster** [comment]
> With Strapi 4.25.1 and strapi-plugin-rich-text 1.2.1 I see the following: 

@delux220 ah, I know what the issue might be. These are new fields that you've created, right? or did they have any rich text content?

I'll reopen the issue, thanks for reporting!

**Comment by konstantinruge** [comment]
@delux220 @SalahAdDin I just published a new version (v1.2.2) which should fix the issue. sorry that shouldn't have happened!
